name: build and release

on:
  push:
    branches:
      - main
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-22.04
    container: aleksanderlm/nrf-zephyr-build-environment:v2.5.0.2
    steps:
      - name: test2
        run: | 
          nrfutil list
          nrfutil toolchain-manager search
