name: build and release

on:
  push:
    branches:
      - main
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted
    container: 
      image: aleksanderlm/nrf-zephyr-build-environment:v2.5.0.3
      volumes: 
        - .:/workdir
    steps:
      - name: test
        run: | 
          which nrfutil
          nrfutil install toolchain-manager
          nrfutil toolchain-manager install --ncs-version v2.5.0
        shell: bash
      - name: test2
        run: nrfutil toolchain-manager launch -- west
        shell: bash
