name: build and release

on:
  push:
    branches:
      - main
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: test2
        run: | 
          nrfutil list
          nrfutil install toolchain-manager
          nrfutil list
          nrfutil toolchain-manager search
          nrfutil toolchain-manager install --ncs-version v2.5.0
