name: build and release

on:
  push:
    branches:
      - main
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted
    container: aleksanderlm/nrf-zephyr-build-environment:v2.5.0.3
    steps:
      - name: test
        run: "nrfutil toolchain-manager launch /bin/bash -- -c west"
