name: build and release

on:
  push:
    branches:
      - main
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: test2
        run: nrfutil toolchain-manager launch -- west
        shell: bash
