name: build and release

on:
  push:
    branches:
      - main
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  build:
    runs-on: self-hosted
    container: 
      image: aleksanderlm/nrf-zephyr-build-environment:v2.5.0.2
      options: --user root
    steps:
    - name: Print Environment Info
      run: |
        whoami
        echo "HOME: $HOME"
        env
    - name: Interactive shell
      run: |
        docker run -it aleksanderlm/nrf-zephyr-build-environment:v2.5.0.2 /bin/bash
        nrfutil list
        nrfutil toolchain-manager search
    - name: test2
      run: | 
        nrfutil list
        nrfutil toolchain-manager search
