name: build and release

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches-ignore:
      - '*'
    tags:
      - v*
  workflow_dispatch: # This event allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: tell run reason
        run: echo ${{ github.event_name }}

      - name: Cache docker image
        uses: actions/cache@v3
        id: docker-cache
        with:
          path: run_reason.txt
          key: ${{ runner.os }}-docker
          restore-keys: ${{ runner.os }}-docker
      
      - name: echo to file
        run: echo ${{ github.event_name }} > run_reason.txt
